SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS C

JOIN ITEM_TREE AS P
ON C.ITEM_ID = P.ITEM_ID

# 부모 아이템의 정보를 더한 TOTAL 테이블
JOIN ITEM_INFO AS T
ON P.PARENT_ITEM_ID = T.ITEM_ID

WHERE T.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;