SELECT B.CATEGORY, SUM(BS.BOOK_SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN 
    (SELECT BOOK_ID, SUM(SALES) AS BOOK_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01'
    AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID) AS BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;
